package db;
// Generated Feb 12, 2017 2:00:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FestivalGroup generated by hbm2java
 */
public class FestivalGroup  implements java.io.Serializable {


     private Integer idfestivalGroup;
     private String name;
     private Integer avgRating;
     private Integer numberOfRatings;
     private Set<Media> medias = new HashSet<Media>(0);
     private Set<Comment> comments = new HashSet<Comment>(0);
     private Set<Festival> festivals = new HashSet<Festival>(0);

    public FestivalGroup() {
    }

	
    public FestivalGroup(String name) {
        this.name = name;
    }
    public FestivalGroup(String name, Integer avgRating, Integer numberOfRatings, Set<Media> medias, Set<Comment> comments, Set<Festival> festivals) {
       this.name = name;
       this.avgRating = avgRating;
       this.numberOfRatings = numberOfRatings;
       this.medias = medias;
       this.comments = comments;
       this.festivals = festivals;
    }
   
    public Integer getIdfestivalGroup() {
        return this.idfestivalGroup;
    }
    
    public void setIdfestivalGroup(Integer idfestivalGroup) {
        this.idfestivalGroup = idfestivalGroup;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getAvgRating() {
        return this.avgRating;
    }
    
    public void setAvgRating(Integer avgRating) {
        this.avgRating = avgRating;
    }
    public Integer getNumberOfRatings() {
        return this.numberOfRatings;
    }
    
    public void setNumberOfRatings(Integer numberOfRatings) {
        this.numberOfRatings = numberOfRatings;
    }
    public Set<Media> getMedias() {
        return this.medias;
    }
    
    public void setMedias(Set<Media> medias) {
        this.medias = medias;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }
    public Set<Festival> getFestivals() {
        return this.festivals;
    }
    
    public void setFestivals(Set<Festival> festivals) {
        this.festivals = festivals;
    }




}


