package db;
// Generated Feb 12, 2017 2:00:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Festival generated by hbm2java
 */
public class Festival  implements java.io.Serializable {


     private Integer idfestival;
     private FestivalGroup festivalGroup;
     private int year;
     private Date start;
     private Date end;
     private String location;
     private int maxReservationsPerClient;
     private int bundlePrice;
     private String description;
     private int visits;
     private int ticketsBought;
     private String facebook;
     private String twitter;
     private String instagram;
     private String youtube;
     private Set<Day> days = new HashSet<Day>(0);
     private Set<Performance> performances = new HashSet<Performance>(0);

    public Festival() {
    }

	
    public Festival(FestivalGroup festivalGroup, int year, Date start, Date end, String location, int maxReservationsPerClient, int bundlePrice, int visits, int ticketsBought) {
        this.festivalGroup = festivalGroup;
        this.year = year;
        this.start = start;
        this.end = end;
        this.location = location;
        this.maxReservationsPerClient = maxReservationsPerClient;
        this.bundlePrice = bundlePrice;
        this.visits = visits;
        this.ticketsBought = ticketsBought;
    }
    public Festival(FestivalGroup festivalGroup, int year, Date start, Date end, String location, int maxReservationsPerClient, int bundlePrice, String description, int visits, int ticketsBought, String facebook, String twitter, String instagram, String youtube, Set<Day> days, Set<Performance> performances) {
       this.festivalGroup = festivalGroup;
       this.year = year;
       this.start = start;
       this.end = end;
       this.location = location;
       this.maxReservationsPerClient = maxReservationsPerClient;
       this.bundlePrice = bundlePrice;
       this.description = description;
       this.visits = visits;
       this.ticketsBought = ticketsBought;
       this.facebook = facebook;
       this.twitter = twitter;
       this.instagram = instagram;
       this.youtube = youtube;
       this.days = days;
       this.performances = performances;
    }
   
    public Integer getIdfestival() {
        return this.idfestival;
    }
    
    public void setIdfestival(Integer idfestival) {
        this.idfestival = idfestival;
    }
    public FestivalGroup getFestivalGroup() {
        return this.festivalGroup;
    }
    
    public void setFestivalGroup(FestivalGroup festivalGroup) {
        this.festivalGroup = festivalGroup;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public int getMaxReservationsPerClient() {
        return this.maxReservationsPerClient;
    }
    
    public void setMaxReservationsPerClient(int maxReservationsPerClient) {
        this.maxReservationsPerClient = maxReservationsPerClient;
    }
    public int getBundlePrice() {
        return this.bundlePrice;
    }
    
    public void setBundlePrice(int bundlePrice) {
        this.bundlePrice = bundlePrice;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getVisits() {
        return this.visits;
    }
    
    public void setVisits(int visits) {
        this.visits = visits;
    }
    public int getTicketsBought() {
        return this.ticketsBought;
    }
    
    public void setTicketsBought(int ticketsBought) {
        this.ticketsBought = ticketsBought;
    }
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }
    public String getTwitter() {
        return this.twitter;
    }
    
    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }
    public String getInstagram() {
        return this.instagram;
    }
    
    public void setInstagram(String instagram) {
        this.instagram = instagram;
    }
    public String getYoutube() {
        return this.youtube;
    }
    
    public void setYoutube(String youtube) {
        this.youtube = youtube;
    }
    public Set<Day> getDays() {
        return this.days;
    }
    
    public void setDays(Set<Day> days) {
        this.days = days;
    }
    public Set<Performance> getPerformances() {
        return this.performances;
    }
    
    public void setPerformances(Set<Performance> performances) {
        this.performances = performances;
    }




}


