package db;
// Generated Feb 12, 2017 2:00:16 PM by Hibernate Tools 4.3.1



/**
 * Media generated by hbm2java
 */
public class Media  implements java.io.Serializable {


     private Integer idmedia;
     private FestivalGroup festivalGroup;
     private int type;
     private Byte approved;

    public Media() {
    }

	
    public Media(FestivalGroup festivalGroup, int type) {
        this.festivalGroup = festivalGroup;
        this.type = type;
    }
    public Media(FestivalGroup festivalGroup, int type, Byte approved) {
       this.festivalGroup = festivalGroup;
       this.type = type;
       this.approved = approved;
    }
   
    public Integer getIdmedia() {
        return this.idmedia;
    }
    
    public void setIdmedia(Integer idmedia) {
        this.idmedia = idmedia;
    }
    public FestivalGroup getFestivalGroup() {
        return this.festivalGroup;
    }
    
    public void setFestivalGroup(FestivalGroup festivalGroup) {
        this.festivalGroup = festivalGroup;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public Byte getApproved() {
        return this.approved;
    }
    
    public void setApproved(Byte approved) {
        this.approved = approved;
    }




}


