package db;
// Generated Feb 12, 2017 2:00:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private String name;
     private String surname;
     private String username;
     private String password;
     private int phone;
     private String email;
     private int type;
     private Integer failedReservations;
     private String notification;
     private Date lastLogin;
     private Integer warnings;
     private Set<Comment> comments = new HashSet<Comment>(0);
     private Set<Reservation> reservations = new HashSet<Reservation>(0);

    public User() {
    }

	
    public User(String name, String surname, String username, String password, int phone, String email, int type) {
        this.name = name;
        this.surname = surname;
        this.username = username;
        this.password = password;
        this.phone = phone;
        this.email = email;
        this.type = type;
    }
    public User(String name, String surname, String username, String password, int phone, String email, int type, Integer failedReservations, String notification, Date lastLogin, Integer warnings, Set<Comment> comments, Set<Reservation> reservations) {
       this.name = name;
       this.surname = surname;
       this.username = username;
       this.password = password;
       this.phone = phone;
       this.email = email;
       this.type = type;
       this.failedReservations = failedReservations;
       this.notification = notification;
       this.lastLogin = lastLogin;
       this.warnings = warnings;
       this.comments = comments;
       this.reservations = reservations;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getPhone() {
        return this.phone;
    }
    
    public void setPhone(int phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public Integer getFailedReservations() {
        return this.failedReservations;
    }
    
    public void setFailedReservations(Integer failedReservations) {
        this.failedReservations = failedReservations;
    }
    public String getNotification() {
        return this.notification;
    }
    
    public void setNotification(String notification) {
        this.notification = notification;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    public Integer getWarnings() {
        return this.warnings;
    }
    
    public void setWarnings(Integer warnings) {
        this.warnings = warnings;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }




}


